[window]
opacity = 0.7
blur = true
padding = { x = 8, y = 5 }

[font]
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }

[general]
import = [
	"~/.config/alacritty/catppuccin-macchiato.toml"
]
